# Generated by Django 5.2.8 on 2026-01-15 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="New Project", max_length=256)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Taxonomy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Taxonomy",
                "verbose_name_plural": "Taxonomies",
            },
        ),
        migrations.CreateModel(
            name="ElementaryFlowCompartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "parent_compartment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent compartment if this is a sub-compartment.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_compartments",
                        to="core.elementaryflowcompartment",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elementary_flow_compartments",
                        to="core.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processes",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Process",
                "verbose_name_plural": "Processes",
            },
        ),
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dimensions",
                        to="core.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "taxonomy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="core.taxonomy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Good",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goods",
                        to="core.project",
                    ),
                ),
                (
                    "terms",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Terms associated with this entity.",
                        related_name="%(class)s_terms",
                        to="core.term",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConservedEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text="Short name or symbol for the conserved entity (e.g., 'C' for Carbon).",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "molar_mass",
                    models.FloatField(
                        blank=True,
                        help_text="Molar mass of the conserved entity in g/mol.",
                        null=True,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conserved_entities",
                        to="core.project",
                    ),
                ),
                (
                    "terms",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Terms associated with this entity.",
                        related_name="%(class)s_terms",
                        to="core.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conserved Entity",
                "verbose_name_plural": "Conserved Entities",
            },
        ),
        migrations.CreateModel(
            name="TransformableEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text="Short name or symbol for the transformable entity (e.g., 'CH4' for Methane).",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transformable_entities",
                        to="core.project",
                    ),
                ),
                (
                    "terms",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Terms associated with this entity.",
                        related_name="%(class)s_terms",
                        to="core.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transformable Entity",
                "verbose_name_plural": "Transformable Entities",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("symbol", models.CharField(max_length=32, unique=True)),
                (
                    "dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="core.dimension",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransformableEntityContainConservedEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ratio",
                    models.FloatField(
                        help_text="Ratio of conserved entity per unit of transformable entity."
                    ),
                ),
                (
                    "conserved_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transformables",
                        to="core.conservedentity",
                    ),
                ),
                (
                    "transformable_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conserveds",
                        to="core.transformableentity",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="Unit of the ratio.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.unit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoodContainTransformableEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.FloatField(
                        help_text="Quantity of transformable entity in the good."
                    ),
                ),
                (
                    "good",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transformables",
                        to="core.good",
                    ),
                ),
                (
                    "transformable_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goods",
                        to="core.transformableentity",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="Unit of the quantity.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.unit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoodContainGood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.FloatField(
                        help_text="Quantity of child good in the parent good."
                    ),
                ),
                (
                    "child_good",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supergoods",
                        to="core.good",
                    ),
                ),
                (
                    "parent_good",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subgoods",
                        to="core.good",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="Unit of the quantity.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.unit",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="good",
            name="reference_unit",
            field=models.ForeignKey(
                help_text="Reference unit for the good.",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.unit",
            ),
        ),
        migrations.CreateModel(
            name="ElementaryFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.FloatField(
                        help_text="Quantity of conserved entity in the elementary flow."
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("input", "Input"), ("output", "Output")],
                        help_text="Indicates whether the conserved entity is an input to or an output from the process.",
                        max_length=10,
                    ),
                ),
                (
                    "conserved_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elementary_flows",
                        to="core.conservedentity",
                    ),
                ),
                (
                    "compartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elementary_flows",
                        to="core.elementaryflowcompartment",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elementary_flows",
                        to="core.process",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="Unit of the quantity.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.unit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EconomicFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.FloatField(
                        help_text="Quantity of good in the economic flow."
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("input", "Input"), ("output", "Output")],
                        help_text="Indicates whether the good is an input to or an output from the process.",
                        max_length=10,
                    ),
                ),
                (
                    "is_byproduct",
                    models.BooleanField(
                        default=False,
                        help_text="True if the good is a byproduct of the process, False otherwise.",
                    ),
                ),
                (
                    "good",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="economic_flows",
                        to="core.good",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="economic_flows",
                        to="core.process",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="Unit of the quantity.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.unit",
                    ),
                ),
            ],
        ),
    ]
